name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Safety (SCA)
      run: |
        pip install safety
        mkdir -p reports
        safety check --full-report > reports/safety-report.txt || true

    - name: Upload Safety Report
      uses: actions/upload-artifact@v4
      with:
        name: safety-report
        path: reports/safety-report.txt

    - name: Run Bandit (SAST)
      run: |
        pip install bandit
        mkdir -p reports
        bandit -r app/ -f html -o reports/bandit-report.html || true

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: reports/bandit-report.html

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and Tag Docker Image
  run: |
    docker build -t mqtt-token-checker:latest .
    docker tag mqtt-token-checker:latest ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker:latest

    - name: Install Trivy
     run: |
      sudo apt-get update
      sudo apt-get install -y wget
      wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.51.1_Linux-64bit.deb
      sudo dpkg -i trivy_0.51.1_Linux-64bit.deb

    - name: Scan Docker Image with Trivy
      run: |
       mkdir -p reports
       trivy image --format json -o reports/report.json --severity CRITICAL,HIGH mqtt-token-checker:latest

    - name: Evaluate Vulnerability Risk Score
      run: |
       sudo apt-get install -y jq
       HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' reports/report.json)
       echo "Found $HIGH high or critical vulnerabilities"
       if [ "$HIGH" -gt 5 ]; then
         echo "Too many critical vulnerabilities. Failing build."
         exit 1
       fi

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
        name: trivy-report
        path: reports/report.json


    

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker:latest

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker
          docker stop mqtt-token-checker || true
          docker rm mqtt-token-checker || true
          docker run -d --name mqtt-token-checker ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker
