name: DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Safety (SCA)
      run: |
        pip install safety
        mkdir -p reports
        safety check --full-report > reports/safety-report.txt || true

    - name: Upload Safety Report
      uses: actions/upload-artifact@v4
      with:
         name: safety-report
         path: reports/safety-report.txt

    - name: Run Bandit (SAST)
      run: |
        mkdir -p reports
        bandit -r app/ -f html -o reports/bandit-report.html || true

    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: "p/default"

    - name: Upload Bandit Report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: reports/bandit-report.html

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
    - name: Build and tag the image
      run: |
          docker build -t mqtt-token-checker:latest .
          docker tag mqtt-token-checker:latest ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker:latest
      
    - name: Scan Docker Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: mqtt-token-checker
        format: table
        exit-code: 1
        severity: CRITICAL,HIGH


    - name: Run Dockle (Docker Best Practices)
      uses: goodwithtech/dockle-action@v1
      with:
          image: mqtt-token-checker:latest

    - name: Evaluate Vulnerability Risk Score
      run: |
          sudo apt-get install -y jq
          docker save mqtt-token-checker:latest | trivy image --input - --format json -o report.json
          HIGH=$(jq '[.Results[].Vulnerabilities[] | select(.Severity == "HIGH" or .Severity == "CRITICAL")] | length' report.json)
          echo "Found $HIGH high or critical vulnerabilities"
          if [ "$HIGH" -gt 5 ]; then
            echo "Too many critical vulnerabilities. Failing build."
            exit 1
          fi

    - name: Upload Trivy Report
      uses: actions/upload-artifact@v4
      with:
          name: trivy-report
          path: report.json
          
    - name: Push the image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mqtt-token-checker:latest
          
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Execute remote SSH commands using password
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull my23007/mqtt-token-checker || true
          docker stop mqtt-token-checker || true
          docker rm mqtt-token-checker || true
          docker run -d --name mqtt-token-checker my23007/mqtt-token-checker
